namespace QuantumBuild.Tests.Unit.Infrastructure;

public class MigrationStructureTests
{
    private static readonly string MigrationsPath = FindMigrationsPath();

    private static string FindMigrationsPath()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null && !File.Exists(Path.Combine(dir.FullName, "QuantumBuild.sln")))
            dir = dir.Parent;

        if (dir == null)
            throw new InvalidOperationException(
                "Could not locate solution root (QuantumBuild.sln not found in any ancestor directory).");

        return Path.Combine(dir.FullName, "src", "Core", "QuantumBuild.Core.Infrastructure", "Migrations");
    }

    /// <summary>
    /// Check A — every main migration .cs has a matching .Designer.cs companion.
    /// A hand-written .cs without its .Designer.cs causes EF to silently skip the migration on startup
    /// because the [Migration] attribute EF reads lives in the .Designer.cs partial class declaration.
    /// </summary>
    [Fact]
    public void EveryMigrationFile_HasMatchingDesignerCs()
    {
        var migrationFiles = Directory
            .GetFiles(MigrationsPath, "*.cs")
            .Where(f => !f.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase))
            .Where(f => !Path.GetFileName(f).EndsWith("ModelSnapshot.cs", StringComparison.OrdinalIgnoreCase))
            .ToList();

        var orphans = migrationFiles
            .Where(f =>
            {
                var designerPath = Path.Combine(
                    Path.GetDirectoryName(f)!,
                    Path.GetFileNameWithoutExtension(f) + ".Designer.cs");
                return !File.Exists(designerPath);
            })
            .Select(f => Path.GetFileName(f))
            .OrderBy(x => x)
            .ToList();

        orphans.Should().BeEmpty(
            $"every migration .cs must have a matching .Designer.cs companion (EF silently skips migrations " +
            $"whose [Migration] attribute only exists in the .Designer.cs partial class), " +
            $"but these are missing their companion:{Environment.NewLine}" +
            string.Join(Environment.NewLine, orphans.Select(f => $"  - {f}")));
    }

    /// <summary>
    /// Check B — every .Designer.cs has the EF-generated markers:
    ///   1. First line is exactly "// &lt;auto-generated /&gt;"
    ///   2. Contains [Migration("timestamp_name")] matching the filename exactly.
    /// Both markers are written by "dotnet ef migrations add"; their absence means the file was
    /// hand-authored or had its header stripped, making it untrustworthy as a valid migration descriptor.
    /// </summary>
    [Fact]
    public void EveryDesignerCs_HasAutoGeneratedMarkerAndCorrectMigrationAttribute()
    {
        var designerFiles = Directory
            .GetFiles(MigrationsPath, "*.Designer.cs")
            .OrderBy(f => f)
            .ToList();

        var failures = new List<string>();

        foreach (var file in designerFiles)
        {
            var baseName = Path.GetFileName(file).Replace(".Designer.cs", "", StringComparison.OrdinalIgnoreCase);
            var lines = File.ReadAllLines(file);
            var content = File.ReadAllText(file);

            var issues = new List<string>();

            if (lines.Length == 0 || lines[0].TrimEnd() != "// <auto-generated />")
                issues.Add("first line is not '// <auto-generated />'");

            var expectedAttribute = $"[Migration(\"{baseName}\")]";
            if (!content.Contains(expectedAttribute, StringComparison.Ordinal))
                issues.Add($"does not contain {expectedAttribute}");

            if (issues.Count > 0)
                failures.Add($"  - {Path.GetFileName(file)}: {string.Join("; ", issues)}");
        }

        failures.Should().BeEmpty(
            $"every .Designer.cs must have the '// <auto-generated />' header on line 1 and a " +
            $"[Migration(\"...\")) attribute whose argument matches the filename exactly " +
            $"(generated by 'dotnet ef migrations add' — hand-authored files lack these markers), " +
            $"but these fail:{Environment.NewLine}" +
            string.Join(Environment.NewLine, failures));
    }
}
